version: 1.0
provider:
  name: openfaas
  gateway: http://9f591d11-f4fb-4142-880a-e74e27283fbb.k8s.civo.com:31112
functions:
  kitchen-web:
    lang: dockerfile
    handler: ./kitchen-web
    image: 15091983/kitchen-web:latest
  kitchen-api:
    lang: dockerfile
    handler: ./kitchen-api
    image: 15091983/kitchen-api:latest
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      PORT: 8080
      exec_timeout: 2h
    secrets:
      - secret-appsettings
