rbac:
  create: true
resourcesToWatch:
  deployment: true
  replicationcontroller: false
  replicaset: true
  daemonset: false
  services: true
  pod: true
  job: false
  node: false
  clusterrole: true
  serviceaccount: true
  persistentvolume: false
  namespace: false
  secret: false
  configmap: false
  ingress: false
slack:
  enabled: true
  channel: 'kitchen'
  token: 'xoxb-435046142385-1536257083442-iwZYgTCep0vMjfc5VctWaCz2'
serviceAccount:
  create: true
  name: "kubewatch"