### STAGE 1: Build ###
FROM node:16 AS build
WORKDIR '/app'
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

### STAGE 2: Run ###
FROM nginx:alpine
COPY --from=build /app/dist/ /usr/share/nginx/html

#Copy default nginx configuration
COPY ./nginx.heroku.conf /etc/nginx/conf.d/default.conf
CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'